// Generated by gencpp from file turtlebot_control/setVel.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_CONTROL_MESSAGE_SETVEL_H
#define TURTLEBOT_CONTROL_MESSAGE_SETVEL_H

#include <ros/service_traits.h>


#include <turtlebot_control/setVelRequest.h>
#include <turtlebot_control/setVelResponse.h>


namespace turtlebot_control
{

struct setVel
{

typedef setVelRequest Request;
typedef setVelResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct setVel
} // namespace turtlebot_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot_control::setVel > {
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::turtlebot_control::setVel&) { return value(); }
};

template<>
struct DataType< ::turtlebot_control::setVel > {
  static const char* value()
  {
    return "turtlebot_control/setVel";
  }

  static const char* value(const ::turtlebot_control::setVel&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot_control::setVelRequest> should match
// service_traits::MD5Sum< ::turtlebot_control::setVel >
template<>
struct MD5Sum< ::turtlebot_control::setVelRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_control::setVel >::value();
  }
  static const char* value(const ::turtlebot_control::setVelRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_control::setVelRequest> should match
// service_traits::DataType< ::turtlebot_control::setVel >
template<>
struct DataType< ::turtlebot_control::setVelRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot_control::setVel >::value();
  }
  static const char* value(const ::turtlebot_control::setVelRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot_control::setVelResponse> should match
// service_traits::MD5Sum< ::turtlebot_control::setVel >
template<>
struct MD5Sum< ::turtlebot_control::setVelResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot_control::setVel >::value();
  }
  static const char* value(const ::turtlebot_control::setVelResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot_control::setVelResponse> should match
// service_traits::DataType< ::turtlebot_control::setVel >
template<>
struct DataType< ::turtlebot_control::setVelResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot_control::setVel >::value();
  }
  static const char* value(const ::turtlebot_control::setVelResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT_CONTROL_MESSAGE_SETVEL_H
