// Generated by gencpp from file turtlebot_control/setVelRequest.msg
// DO NOT EDIT!


#ifndef TURTLEBOT_CONTROL_MESSAGE_SETVELREQUEST_H
#define TURTLEBOT_CONTROL_MESSAGE_SETVELREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot_control
{
template <class ContainerAllocator>
struct setVelRequest_
{
  typedef setVelRequest_<ContainerAllocator> Type;

  setVelRequest_()
    {
    }
  setVelRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::turtlebot_control::setVelRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot_control::setVelRequest_<ContainerAllocator> const> ConstPtr;

}; // struct setVelRequest_

typedef ::turtlebot_control::setVelRequest_<std::allocator<void> > setVelRequest;

typedef boost::shared_ptr< ::turtlebot_control::setVelRequest > setVelRequestPtr;
typedef boost::shared_ptr< ::turtlebot_control::setVelRequest const> setVelRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot_control::setVelRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot_control::setVelRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace turtlebot_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot_control::setVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot_control::setVelRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot_control::setVelRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::turtlebot_control::setVelRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot_control/setVelRequest";
  }

  static const char* value(const ::turtlebot_control::setVelRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::turtlebot_control::setVelRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct setVelRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot_control::setVelRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::turtlebot_control::setVelRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT_CONTROL_MESSAGE_SETVELREQUEST_H
